# Notebook Lab 01: Numpy Basics
## Objective
By the end of this exercise, you will:

- Understand NumPy arrays and their advantages over lists.
- Perform basic operations on arrays.
- Use indexing, slicing, and reshaping.
- Perform mathematical operations and aggregations.

### Step 1: Importing NumPy and Creating Arrays
Run the following code to create NumPy arrays:

In [1]:
import numpy as np

# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

# Checking array type
print("Type:", type(arr1))
print("Shape of arr2:", arr2.shape)
print("Data Type of arr1:", arr1.dtype)



1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape of arr2: (2, 3)
Data Type of arr1: int64


### **<font color='red'>Your Task:</font>**

- Create a 3×3 matrix with numbers from 1 to 9.
- Create an array of zeros with shape (2, 4).

### Step 2: NumPy Array Operations
Perform arithmetic operations on arrays:

In [2]:
# Formatting a date
arr = np.array([10, 20, 30, 40])

# Arithmetic operations
print("Array + 5:", arr + 5)
print("Array * 2:", arr * 2)
print("Array Squared:", arr ** 2)

# Element-wise addition
arr2 = np.array([1, 2, 3, 4])
print("Element-wise Addition:", arr + arr2)

Array + 5: [15 25 35 45]
Array * 2: [20 40 60 80]
Array Squared: [ 100  400  900 1600]
Element-wise Addition: [11 22 33 44]


### **<font color='red'>Your Task:</font>**

- Create two 1D arrays of length 5 and perform element-wise multiplication.
- Subtract a scalar value from a NumPy array.

### Step 3: Indexing and Slicing
Run the code below and observe the results:

In [3]:
arr = np.array([10, 20, 30, 40, 50])

# Accessing elements
print("First element:", arr[0])
print("Last element:", arr[-1])

# Slicing
print("First three elements:", arr[:3])
print("Elements from index 2 onwards:", arr[2:])


Converted Date: 2025-02-11 14:30:00


For 2D arrays:

In [ ]:
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Accessing elements
print("Element at (1,1):", matrix[1,1])

# Slicing
print("First row:", matrix[0])
print("Last two columns:\n", matrix[:, 1:])

### **<font color='red'>Your Task:</font>**

- Extract the first two rows of a 3×3 matrix.
- Extract all elements in the second column.

### Step 4: Reshaping and Transposing
Reshape and manipulate array dimensions:

In [3]:
arr = np.arange(1, 13)  # Creates an array from 1 to 12
print("Original Array:", arr)

# Reshaping into a 3×4 matrix
reshaped_arr = arr.reshape(3, 4)
print("Reshaped Array:\n", reshaped_arr)

# Transposing
transposed = reshaped_arr.T
print("Transposed Array:\n", transposed)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transposed Array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### **<font color='red'>Your Task:</font>**

- Create a 1D array of 16 numbers and reshape it into a 4×4 matrix.
- Transpose a 3×5 matrix.

### Step 5: NumPy Aggregations
NumPy provides powerful functions for summarizing data:

In [7]:
arr = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Standard Deviation:", np.std(arr))

Current UTC Time: 2025-02-11 23:14:53.989746+00:00
Time in New York: 2025-02-11 18:14:53.989746-05:00


For 2D arrays:

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Column-wise Sum:", np.sum(matrix, axis=0))
print("Row-wise Mean:", np.mean(matrix, axis=1))

### **<font color='red'>Your Task:</font>**
- Find the max value of a 2D array column-wise.
- Compute the standard deviation of a 4×4 matrix.

### Step 7: Random Numbers in NumPy
Generate random arrays:



In [4]:
# Random integer between 1 and 100
rand_int = np.random.randint(1, 100, size=(3, 3))
print("Random 3×3 Matrix:\n", rand_int)

# Random numbers between 0 and 1
rand_float = np.random.rand(4)
print("Random Float Array:", rand_float)

Random 3×3 Matrix:
 [[87 68 34]
 [55  4 83]
 [75  8 32]]
Random Float Array: [0.12203259 0.58211068 0.50733488 0.0937822 ]


### **<font color='red'>Your Task:</font>**
- Generate a 5×5 matrix with random numbers between 10 and 50.
- Create a 1D array of 6 random numbers from a normal distribution.


### Final Task

Write a NumPy-based Python program that:

- Creates a random 4×4 matrix of integers between 1 and 100.
- Finds the sum of each row.
- Finds the maximum value of each column.
- Reshapes it into a 2×8 array and prints the result.
- **Hint:** Use np.random.randint(), np.sum(), np.max(), and reshape().

Example output:

Original 4×4 Matrix:

[[12 45 78 23]
 [67 89 34 56]
 [90 12 44 67]
 [22 49 37 85]]

Row-wise Sum:
[158, 246, 213, 193]

Column-wise Max:
[90, 89, 78, 85]

Reshaped 2×8 Array:
[[12 45 78 23 67 89 34 56]
 [90 12 44 67 22 49 37 85]]